name: 'Run all tests on and update coverage on push'
run-name: ${{ github.actor }} initiated a push request

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  call_chk_devcontainer:
    name: Checking for valid dev container image
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/chk_devcontainer_img.yml
    with:
      image-id: devops-demo-img:latest
    secrets:
      secr-token: ${{ secrets.GITHUB_TOKEN }}

  run_tests:
    runs-on: ubuntu-latest
    needs: call_chk_devcontainer
    permissions:
      contents: write
    env:
      IMAGE_NAME: ${{ needs.call_chk_devcontainer.outputs.image-path }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Pull dev container
        run: docker pull ${IMAGE_NAME}
      - name: Run tests inside container
        run: docker run --rm --mount type=bind,src=${{ github.workspace }},dst=/workspace ${IMAGE_NAME} sh -c "cd /workspace;mvn compile && mvn test"
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: target/site/jacoco/
          retention-days: 7

  update_coverage_report:
    needs: run_tests
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/test-coverage-report.yml
